version: '3.3'
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - front_net
      - back_net

  fluentd:
    image: ${USERNAME}/fluentd
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - front_net
      - back_net

  elasticsearch:
    image: elasticsearch:7.3.1
    expose:
      - 9200
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - transport.host=localhost
      - transport.tcp.port=9300
      - http.port=9200
      - http.host=0.0.0.0
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - front_net
      - back_net

  kibana:
    image: kibana:7.3.1
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - "5601:5601"
    networks:
      - front_net
      - back_net

networks:
  front_net:

  back_net:
