kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: plzNeGudo/oXYGGcZv3E08q6Inu/1d8/QtyfYu3LKgc=
      - identity: {}
